### PR TITLE
Fixed layer filtering for the search API

### PR DESCRIPTION
**Pull request by mihaicosareanu-bolt**
:wave: I did some awesome work for the Pelias project and would love for everyone to have a look at it and provide feedback.

---
#### Here's the reason for this change :rocket:

- Fixes https://github.com/pelias/api/issues/1391
---
#### Here's what actually got changed :clap:

- Added a hard filter for layers on the address_search_using_ids query

---
#### Here's how others can test the changes :eyes:

In the issue linked above I described how to reproduce.

### CODE REVIEW

**Comment by missinglink** [comment]
Thanks for the PR, I don't recall why the layers filter was never present for this query, anyone remember?

**Comment by Joxit** [comment]
Hum... Maybe for fallback ? 

For example `/v1/search?layers=address&text=20 unknown road Paris France` will return Paris or `/v1/search?layers=address&text=999999 Boulevard Saint Germain Paris France` will return  `Boulevard Saint Germain, Paris, France` ? Or it was forgotten :sweat_smile: 

But yes, this may be unexpected behaviour.

**Comment by orangejulius** [comment]
I think the idea was that these queries have layer filters "built in" to them. There are sections that search for addresses and must be in the address layer, streets that must be in the street layer, etc. But the ability to limit what layers can come back at all wasn't a part of that design. It might have been an oversight, but I also think that as we added more complexity over time (the queries predate our importing of streets, for example), some bugs crept in.

**Comment by orangejulius** [comment]
Anyways, this PR looks great, we will test it out real quick and hopefully merge it right away :) Thanks!

**Comment by mihaicosareanu-bolt** [comment]
Wow, thanks a lot guys! You are always so responsive! :) 🚀

**Pull request merged**
