### PR TITLE
Add boundary.country filter to /v1/autocomplete

### PR DESCRIPTION
**Pull request by orangejulius**
It works exactly the same as in `/search`, no surprises here!

Connects https://github.com/pelias/pelias/issues/403

### CODE REVIEW

**Comment by orangejulius** [comment]
It works!
screenshot from 2016-08-12 16-35-53

**Comment by trescube** [comment]
:shipit:

**Comment by dianashk** [comment]
LGTM Wow that was quick!

**Comment by missinglink** [comment]
cc/ @campreb

**Comment by missinglink** [comment]
in production now @campreb

eg:
```
/v1/autocomplete?boundary.country=NZ&text=shortland st, auckland
```

**Pull request merged**
