### PR TITLE
Fix for #1077, fail to search `Saint..` cities in structured queries

### LINKED ISSUE #1077: Structured geocoding fail with `Saint` in locality
Hi,
I'm using pelias-api v3.32.14 and pelias does not found `Saint-Leu-la-Forêt` when i'm sending request like `/v1/search/structured?locality=Saint-Leu-la-Forêt&country=France` but  by dropping Saint word, it works fine (`/v1/search/structured?locality=Leu-la-Forêt&country=France`). 

What I receive:
```http
GET /v1/search/structured?locality=Saint-Leu-la-Forêt&country=France HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8

{
    "bbox": [
        -5.132188, 
        41.365694, 
        9.560119, 
        51.087167
    ], 
    "features": [
        {
            "bbox": [
                -5.132188, 
                41.365694, 
                9.560119, 
                51.087167
            ], 
            "geometry": {
                "coordinates": [
                    2.549047, 
                    46.698481
                ], 
                "type": "Point"
            }, 
            "properties": {
                "accuracy": "centroid", 
                "confidence": 0.1, 
                "country": "France", 
                "country_a": "FRA", 
                "country_gid": "whosonfirst:country:85633147", 
                "gid": "whosonfirst:country:85633147", 
                "id": "85633147", 
                "label": "France", 
                "layer": "country", 
                "match_type": "fallback", 
                "name": "France", 
                "source": "whosonfirst", 
                "source_id": "85633147"
            }, 
            "type": "Feature"
        }, 
        {
            "geometry": {
                "coordinates": [
                    2, 
                    46
                ], 
                "type": "Point"
            }, 
            "properties": {
                "accuracy": "centroid", 
                "confidence": 0.1, 
                "country": "France", 
                "country_a": "FRA", 
                "country_gid": "whosonfirst:country:85633147", 
                "gid": "geonames:country:3017382", 
                "id": "3017382", 
                "label": "France", 
                "layer": "country", 
                "match_type": "fallback", 
                "name": "Republic of France", 
                "source": "geonames", 
                "source_id": "3017382"
            }, 
            "type": "Feature"
        }
    ], 
    "geocoding": {
        "attribution": "http://places.jawg.io/v1/attribution", 
        "engine": {
            "author": "Mapzen", 
            "name": "Pelias", 
            "version": "1.0"
        }, 
        "query": {
            "lang": {
                "defaulted": true, 
                "iso6391": "en", 
                "iso6393": "eng", 
                "name": "English"
            }, 
            "parsed_text": {
                "city": "st-leu-la-forêt", 
                "country": "France"
            }, 
            "private": false, 
            "querySize": 20, 
            "size": 10
        }, 
        "timestamp": 1516284787511, 
        "version": "0.2"
    }, 
    "type": "FeatureCollection"
}
```

Expected:
```http
GET /v1/search/structured?locality=Leu-la-Forêt&country=France HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8

{
    "bbox": [
        2.223919, 
        49.000679, 
        2.260122, 
        49.0255182942
    ], 
    "features": [
        {
            "bbox": [
                2.223919, 
                49.000679, 
                2.260122, 
                49.0255182942
            ], 
            "geometry": {
                "coordinates": [
                    2.24499, 
                    49.015873
                ], 
                "type": "Point"
            }, 
            "properties": {
                "accuracy": "centroid", 
                "confidence": 1, 
                "country": "France", 
                "country_a": "FRA", 
                "country_gid": "whosonfirst:country:85633147", 
                "county": "Saint-Leu-La-Foret", 
                "county_gid": "whosonfirst:county:102068113", 
                "gid": "whosonfirst:locality:101751323", 
                "id": "101751323", 
                "label": "Saint-Leu-la-Forêt, France", 
                "layer": "locality", 
                "localadmin": "Saint-Leu-La-Foret", 
                "localadmin_gid": "whosonfirst:localadmin:404361361", 
                "locality": "Saint-Leu-la-Forêt", 
                "locality_gid": "whosonfirst:locality:101751323", 
                "macrocounty": "Pontoise", 
                "macrocounty_gid": "whosonfirst:macrocounty:404228193", 
                "macroregion": "Ile-of-France", 
                "macroregion_gid": "whosonfirst:macroregion:404227465", 
                "match_type": "exact", 
                "name": "Saint-Leu-la-Forêt", 
                "region": "Val-d'Oise", 
                "region_gid": "whosonfirst:region:85683451", 
                "source": "whosonfirst", 
                "source_id": "101751323"
            }, 
            "type": "Feature"
        }
    ], 
    "geocoding": {
        "attribution": "http://places.jawg.io/v1/attribution", 
        "engine": {
            "author": "Mapzen", 
            "name": "Pelias", 
            "version": "1.0"
        }, 
        "query": {
            "lang": {
                "defaulted": true, 
                "iso6391": "en", 
                "iso6393": "eng", 
                "name": "English"
            }, 
            "parsed_text": {
                "city": "leu-la-forêt", 
                "country": "France"
            }, 
            "private": false, 
            "querySize": 20, 
            "size": 10
        }, 
        "timestamp": 1516284832861, 
        "version": "0.2"
    }, 
    "type": "FeatureCollection"
}
```
Where is the elasticsearch request:

```json
{
    "method": "POST",
    "path": "/pelias/_search",
    "body": {
      "query": {
        "function_score": {
          "query": {
            "bool": {
              "minimum_should_match": 1,
              "should": [
                {
                  "bool": {
                    "_name": "fallback.borough",
                    "must": [
                      {
                        "multi_match": {
                          "query": "st-leu-la-forêt",
                          "type": "phrase",
                          "fields": [
                            "parent.borough",
                            "parent.borough_a"
                          ]
                        }
                      },
                      {
                        "multi_match": {
                          "query": "France",
                          "type": "phrase",
                          "fields": [
                            "parent.country",
                            "parent.country_a",
                            "parent.dependency",
                            "parent.dependency_a"
                          ]
                        }
                      }
                    ],
                    "filter": {
                      "term": {
                        "layer": "borough"
                      }
                    }
                  }
                },
                {
                  "bool": {
                    "_name": "fallback.locality",
                    "must": [
                      {
                        "multi_match": {
                          "query": "st-leu-la-forêt",
                          "type": "phrase",
                          "fields": [
                            "parent.locality",
                            "parent.locality_a"
                          ]
                        }
                      },
                      {
                        "multi_match": {
                          "query": "France",
                          "type": "phrase",
                          "fields": [
                            "parent.country",
                            "parent.country_a",
                            "parent.dependency",
                            "parent.dependency_a"
                          ]
                        }
                      }
                    ],
                    "filter": {
                      "term": {
                        "layer": "locality"
                      }
                    }
                  }
                },
                {
                  "bool": {
                    "_name": "fallback.localadmin",
                    "must": [
                      {
                        "multi_match": {
                          "query": "st-leu-la-forêt",
                          "type": "phrase",
                          "fields": [
                            "parent.localadmin",
                            "parent.localadmin_a"
                          ]
                        }
                      },
                      {
                        "multi_match": {
                          "query": "France",
                          "type": "phrase",
                          "fields": [
                            "parent.country",
                            "parent.country_a",
                            "parent.dependency",
                            "parent.dependency_a"
                          ]
                        }
                      }
                    ],
                    "filter": {
                      "term": {
                        "layer": "localadmin"
                      }
                    }
                  }
                },
                {
                  "bool": {
                    "_name": "fallback.dependency",
                    "must": [
                      {
                        "multi_match": {
                          "query": "France",
                          "type": "phrase",
                          "fields": [
                            "parent.dependency",
                            "parent.dependency_a"
                          ]
                        }
                      }
                    ],
                    "filter": {
                      "term": {
                        "layer": "dependency"
                      }
                    }
                  }
                },
                {
                  "bool": {
                    "_name": "fallback.country",
                    "must": [
                      {
                        "multi_match": {
                          "query": "France",
                          "type": "phrase",
                          "fields": [
                            "parent.country",
                            "parent.country_a"
                          ]
                        }
                      }
                    ],
                    "filter": {
                      "term": {
                        "layer": "country"
                      }
                    }
                  }
                }
              ]
            }
          },
          "max_boost": 20,
          "functions": [
            {
              "field_value_factor": {
                "modifier": "log1p",
                "field": "popularity",
                "missing": 1
              },
              "weight": 1
            },
            {
              "field_value_factor": {
                "modifier": "log1p",
                "field": "population",
                "missing": 1
              },
              "weight": 2
            }
          ],
          "score_mode": "avg",
          "boost_mode": "multiply"
        }
      },
      "sort": [
        "_score"
      ],
      "size": 20,
      "track_scores": true
    },
    "query": {
      "search_type": "dfs_query_then_fetch"
    }
  }
```

Same issue for `Sainte-Rose`, `Saint-Remy-Les-Chevreuse`, `Saint-Pavace`....

### PR DESCRIPTION
**Pull request by Joxit**
Fixes #1077

### CODE REVIEW

**Comment by orangejulius** [comment]
Hey @Joxit,
Thanks for this fix. I haven't had the time to test it yet, but I suspect it will break handling of other Saint abbreviations, since this PR effectively reverses the logic from https://github.com/pelias/api/pull/767.

If you have a chance, can you test how some of the cases listed [here](https://github.com/pelias/schema/issues/157#issuecomment-262686739) work after your change? If not, we'll hopefully be able to get to it within the next couple weeks.

**Comment by Joxit** [comment]
Hi,
This PR does not change search queries, but has differents results for structured requests. 

Example with `Saint Marys, PA`

Before:
```http
GET v1/search/structured?locality=Saint Marys&region=PA HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8

{
    "bbox": [
        -78.64852, 
        41.390487, 
        -78.419566, 
        41.523252
    ], 
    "features": [
        {
            "bbox": [
                -78.64852, 
                41.390487, 
                -78.419566, 
                41.523252
            ], 
            "geometry": {
                "coordinates": [
                    -78.534187, 
                    41.459777
                ], 
                "type": "Point"
            }, 
            "properties": {
                "accuracy": "centroid", 
                "confidence": 1, 
                "country": "United States", 
                "country_a": "USA", 
                "country_gid": "whosonfirst:country:85633793", 
                "county": "Elk County", 
                "county_gid": "whosonfirst:county:102081265", 
                "gid": "whosonfirst:locality:101716717", 
                "id": "101716717", 
                "label": "St. Marys, PA, USA", 
                "layer": "locality", 
                "localadmin": "St. Marys", 
                "localadmin_gid": "whosonfirst:localadmin:404486717", 
                "locality": "St. Marys", 
                "locality_gid": "whosonfirst:locality:101716717", 
                "match_type": "exact", 
                "name": "St. Marys", 
                "region": "Pennsylvania", 
                "region_a": "PA", 
                "region_gid": "whosonfirst:region:85688481", 
                "source": "whosonfirst", 
                "source_id": "101716717"
            }, 
            "type": "Feature"
        }
    ], 
    "geocoding": {
        "attribution": "http://places.jawg.io/v1/attribution", 
        "engine": {
            "author": "Mapzen", 
            "name": "Pelias", 
            "version": "1.0"
        }, 
        "query": {
            "lang": {
                "defaulted": true, 
                "iso6391": "en", 
                "iso6393": "eng", 
                "name": "English"
            }, 
            "parsed_text": {
                "city": "st marys", 
                "state": "PA"
            }, 
            "private": false, 
            "querySize": 20, 
            "size": 10
        }, 
        "timestamp": 1517309617785, 
        "version": "0.2"
    }, 
    "type": "FeatureCollection"
}
```

After:
```http
GET v1/search/structured?locality=Saint Marys&region=PA HTTP/1.1

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8

{
    "bbox": [
        -78.56086, 
        40.04178, 
        -75.34074, 
        41.45747
    ], 
    "features": [
        {
            "geometry": {
                "coordinates": [
                    -78.56086, 
                    41.42784
                ], 
                "type": "Point"
            }, 
            "properties": {
                "accuracy": "centroid", 
                "confidence": 1, 
                "country": "United States", 
                "country_a": "USA", 
                "country_gid": "whosonfirst:country:85633793", 
                "county": "Elk County", 
                "county_gid": "whosonfirst:county:102081265", 
                "gid": "geonames:locality:5210117", 
                "id": "5210117", 
                "label": "Saint Marys, PA, USA", 
                "layer": "locality", 
                "localadmin": "St. Marys", 
                "localadmin_gid": "whosonfirst:localadmin:404486717", 
                "locality": "Saint Marys", 
                "locality_gid": "geonames:locality:5210117", 
                "match_type": "exact", 
                "name": "Saint Marys", 
                "region": "Pennsylvania", 
                "region_a": "PA", 
                "region_gid": "whosonfirst:region:85688481", 
                "source": "geonames", 
                "source_id": "5210117"
            }, 
            "type": "Feature"
        }, 
        {
            "geometry": {
                "coordinates": [
                    -78.53418, 
                    41.45747
                ], 
                "type": "Point"
            }, 
            "properties": {
                "accuracy": "centroid", 
                "confidence": 1, 
                "country": "United States", 
                "country_a": "USA", 
                "country_gid": "whosonfirst:country:85633793", 
                "county": "Elk County", 
                "county_gid": "whosonfirst:county:102081265", 
                "gid": "geonames:locality:5210217", 
                "id": "5210217", 
                "label": "City of Saint Marys, PA, USA", 
                "layer": "locality", 
                "localadmin": "St. Marys", 
                "localadmin_gid": "whosonfirst:localadmin:404486717", 
                "locality": "City of Saint Marys", 
                "locality_gid": "geonames:locality:5210217", 
                "match_type": "exact", 
                "name": "City of Saint Marys", 
                "region": "Pennsylvania", 
                "region_a": "PA", 
                "region_gid": "whosonfirst:region:85688481", 
                "source": "geonames", 
                "source_id": "5210217"
            }, 
            "type": "Feature"
        }, 
        {
            "geometry": {
                "coordinates": [
                    -75.34074, 
                    40.04178
                ], 
                "type": "Point"
            }, 
            "properties": {
                "accuracy": "centroid", 
                "confidence": 1, 
                "country": "United States", 
                "country_a": "USA", 
                "country_gid": "whosonfirst:country:85633793", 
                "county": "Delaware County", 
                "county_gid": "whosonfirst:county:102080913", 
                "gid": "geonames:locality:5210213", 
                "id": "5210213", 
                "label": "Saint Marys Seminary, PA, USA", 
                "layer": "locality", 
                "localadmin": "Radnor", 
                "localadmin_gid": "whosonfirst:localadmin:404486571", 
                "locality": "Saint Marys Seminary", 
                "locality_gid": "geonames:locality:5210213", 
                "match_type": "exact", 
                "name": "Saint Marys Seminary", 
                "region": "Pennsylvania", 
                "region_a": "PA", 
                "region_gid": "whosonfirst:region:85688481", 
                "source": "geonames", 
                "source_id": "5210213"
            }, 
            "type": "Feature"
        }
    ], 
    "geocoding": {
        "attribution": "http://places.jawg.io/v1/attribution", 
        "engine": {
            "author": "Mapzen", 
            "name": "Pelias", 
            "version": "1.0"
        }, 
        "query": {
            "lang": {
                "defaulted": true, 
                "iso6391": "en", 
                "iso6393": "eng", 
                "name": "English"
            }, 
            "parsed_text": {
                "city": "saint marys", 
                "state": "PA"
            }, 
            "private": false, 
            "querySize": 20, 
            "size": 10
        }, 
        "timestamp": 1517309648187, 
        "version": "0.2"
    }, 
    "type": "FeatureCollection"
}
```

The query match GeoNames instead of Who's On First because [in GN datas it's Saint-Marys](http://www.geonames.org/5210117/saint-marys.html) and [in WOF it's St. Marys](https://whosonfirst.mapzen.com/spelunker/id/101716717/)... This simplification should perhaps be done in imports instead of API?

**Comment by Joxit** [comment]
This PR is linked to pelias/schema#268

With these changes, all these queries work properly : 

- `/v1/search/structured?locality=St-Leu-la-Forêt&country=France` and `/v1/search/structured?locality=Saint-Leu-la-Forêt&country=France` **Better results than pelias-api master branch**
- `/v1/search/structured?locality=Ste-Rose&region=Reunion` and `/v1/search/structured?locality=Sainte-Rose&region=Reunion`
- `/v1/search/structured?locality=St-Remy-Les-Chevreuse&country=France` and `/v1/search/structured?locality=Saint-Remy-Les-Chevreuse&country=France` **Better results than pelias-api master branch**
- `/v1/search/structured?locality=St-Pavace&country=France` and `/v1/search/structured?locality=Saint-Pavace&country=France` **Better results than pelias-api master branch**
- `/v1/search/structured?locality=St Marys&region=PA` and `/v1/search/structured?locality=Saint Marys&region=PA`
- `/v1/search/structured?locality=St Petersburg&region=FL` and `/v1/search/structured?locality=Saint Petersburg&region=FL`
- `/v1/search/structured?locality=Sault Ste Marie&region=MI` and `/v1/search/structured?locality=Sault Sainte Marie&region=MI`

**Comment by orangejulius** [comment]
It's great to see all those improvements. This change doesn't result in any regressions 

As for your earlier comment about how this could ideally be handled in WOF, I agree, so I looked into things. Most of these records _already_ have the abbreviations expanded as alternate names. For example St Mary's PA:
image

That means [Placeholder](https://github.com/pelias/placeholder) is already aware of these alternate names. However, the structured endpoint doesn't user Placeholder yet. So, this is a great short term fix. In the long term, Placeholder can help fix this issue and many more like it.

Thanks for all the work that went into this :)

**Comment by orangejulius** [comment]
Hi again,
In an effort to make this merge cleanly I have actually reverted these changes in YOUR master branch. Yes, github allows this. Hopefully this doesn't cause any issues, and my apologies if it does. Anyways, our master branch is up to date with these changes, so feel free to sync back up. Thanks again for the PR :)

**Comment by Joxit** [comment]
Hi, thanks :)
You are welcome, I will update my branch too ;)

**Pull request closed without merging**
