### PR TITLE
Check that hit.address exists

### LINKED ISSUE #379: Cannot read property 'zip' of undefined
against dev: `/v1/autocomplete?text=101 saint mark pl 10009`

```
error: [middleware-500] Error: `TypeError: Cannot read property 'zip' of undefined`. Stack trace: `TypeError: Cannot read property 'zip' of undefined
    at checkForDealBreakers (/var/www/pelias/api/middleware/confidenceScore.js:103:107)
    at computeConfidenceScore (/var/www/pelias/api/middleware/confidenceScore.js:57:22)
    at Array.map (native)
    at computeScores (/var/www/pelias/api/middleware/confidenceScore.js:40:23)
    at Layer.handle [as handle_request] (/var/www/pelias/api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/pelias/api/node_modules/express/lib/router/index.js:312:13)
    at /var/www/pelias/api/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/var/www/pelias/api/node_modules/express/lib/router/index.js:330:12)
    at next (/var/www/pelias/api/node_modules/express/lib/router/index.js:271:10)
    at computeDistances (/var/www/pelias/api/middleware/distance.js:24:12)`.
```

IMHO the method name `checkForDealBreakers` is not really clear what it does.

### PR DESCRIPTION
**Pull request by orangejulius**
Fixes #379

### CODE REVIEW

**Comment by missinglink** [comment]
needs MOAR tests!

**Comment by missinglink** [comment]
related https://github.com/pelias/api/issues/379

**Comment by orangejulius** [comment]
Test now added!

**Comment by orangejulius** [comment]
This has to go along with #369 since it fixes a bug that causes 500 errors

**Comment by dianashk** [comment]
:+1:

**Comment by missinglink** [comment]
FYI you can use `t.doesNotThrow()` for more succinct tests if you like.
ref: https://github.com/substack/tape#tdoesnotthrowfn-expected-msg

:+1: from me

**Pull request merged**
