### PR TITLE
better population and popularity boosting

### PR DESCRIPTION
**Pull request by missinglink**
this PR fixes the `popularity` boosting and also adds `population` boosting.

originally I thought there was no population info but that was wrong, so now we use that too, which means:

```bash
/v1/autocomplete?text=london

before:
 1)	London, United Kingdom
 2)	East London, EASTERN CAPE
 3)	New London County, CT
 4)	London, Modum, Buskerud
 5)	London, Dr Ruth Segomotsi Mompati District Municipality, North-West

after:
 1)	London, Greater London, United Kingdom
 2)	London, Middlesex, Ontario
 3)	London, United Kingdom
 4)	London, Madison County, OH
 5)	London, Laurel County, KY
```

also there were issues with the popularity boost applying to ngram matching, now they both use phrase matching instead, so no more boosting partially matched admin results to the top:

(matching **m** **d** and **t**)

```
/v1/search?text=million dollar tacos

before:
 1)	Santa Marã­a Del Tule, Oaxaca
 2)	Tlacolula De Matamoros, Oaxaca
 3)	Tepatitlã¡n De Morelos, Jalisco
 4)	Martã­nez De La Torre, Veracruz de Ignacio de la Llave
 5)	Mã¡rtires De Tacubaya, Oaxaca

after:
 1)	Million Dollar Highway, Ouray County, CO
 2)	2 Million Dollar Lane, Nova Scotia
 3)	1 Million Dollar Lane, Nova Scotia
 4)	Île Million Dollars, Quebec
 5)	Million Dollar Baby, NANTES, Loire-Atlantique
```

since we are no longer only matching against admin0,admin1 and admin2 this solves the 'San Francisco problem':

```
/v1/autocomplete?text=san francisco

before:
 1)	San Francisco Sola, Oaxaca
 2)	San Francisco County
 3)	San Francisco Ixhuatã¡n, Oaxaca
 4)	San Francisco Cahuacuã¡, Oaxaca
 5)	San Francisco Del Rincã³n, Guanajuato

after:
 1)	San Francisco, San Francisco County, CA
 2)	San Francisco, Cordoba
 3)	San Francisco, San José, Heredia
 4)	City of San Francisco, San Francisco, CA
 5)	San Francisco County, CA
```

... plus much better results all around :wine_glass: 

- http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/v1/autocomplete%3Ftext=victoria
- http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/v1/search%3F&text=st%20charles%20way%20york
- http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/v1/search%3Ftext=space%20needl
- http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/v1/search%3F&text=brooklyn
- http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/v1/autocomplete%3Ftext=wales
- http://pelias.compare.s3-website-eu-west-1.amazonaws.com/#/v1/autocomplete%3Ftext=berne

### CODE REVIEW

**Comment by missinglink** [comment]
closes https://github.com/pelias/api/pull/309 (this PR replaces that branch, while can be closed and deleted in favour of this one)

**Comment by missinglink** [comment]
added 2x new commits to balance queries even more, 2ce249a adds more emphasis to local results and  8ceac4c changes the modifier from `sqrt()` to `log1p()` which gives better ranges for mixing with local results.

how we get the correct top 2 results for `?text=london`:
```
 1)	London, Greater London, United Kingdom
 2)	London, Middlesex, Ontario
```

**Comment by dianashk** [comment]
This is awesome! :+1:

**Comment by randymeech** [comment]
:100:

**Pull request merged**
