### PR TITLE
Dockerize Pelias API

### PR DESCRIPTION
**Pull request by hannesj**
I should probably also add some documentation regarding how this should be used.

### CODE REVIEW

**Comment by riordan** [comment]
@hannesj This is great! Thank you. It really means a lot to us that you're so active in the community for this project and actively making the project better.

@heffergm would you mind taking a look over this community contributed pull request?

**Comment by heffergm** [comment]
:+1:

**Comment by orangejulius** [comment]
We on the Pelias team don't know too much about Docker yet, but it's on our todo list. I'm merging this because it definitely won't break anything for now.

**Comment by hannesj** [comment]
@orangejulius thanks!

**Comment by irony** [comment]
@hannesj - do you also have a docker-compose.yml file somewhere? We are evaluating Pelias and would love to see the rest of the setup (elasticsearch, import pipeline, openvenues etc)

**Comment by missinglink** [comment]
@irony the easiest way to evaluate Pelias right now is to sign up for a free API key for our hosted [Mapzen Search](https://mapzen.com/projects/search/) service, although if you need more throughput than the rate limits allow you'll either need to send us an email to ask about getting your limits increased or go down the self-hosted route.

**Pull request merged**
