### PR TITLE
Increment geocodejson format version number in results

### PR DESCRIPTION
**Pull request by dianashk**
Fixes pelias/pelias#315

### CODE REVIEW

**Comment by trescube** [comment]
:shipit:

**Comment by orangejulius** [comment]
Wait, isn't this different than the API version number?

**Comment by dianashk** [comment]
@orangejulius, yes this is incrementing the geocodejson version because we've added a few new params, such as `match_type` and `accuracy` along with the libpostal integration work. We can discuss incrementing the engine version, which we probably should be doing with each new release.

**Comment by orangejulius** [comment]
Ah ok. pelias/pelias#315 mentions the engine version, which one do we want to change?

**Pull request merged**
