### PR TITLE
Debug log full queries and responses between Pelias and Elasticsearch

### PR DESCRIPTION
**Pull request by vesameskanen**
Ability to see full query/response content is very useful when debugging. Logging all queries in Elasticsearch seems to be difficult.

### CODE REVIEW

**Comment by orangejulius** [comment]
Hey @vesameskanen,
This is helpful, thanks! We also have `autocomplete`, `place`, and `reverse` endpoints with their own queries so, if those are interesting to you too, we could print out the queries in more places.

**Comment by vesameskanen** [comment]
I added logging to controller/search, which should cover also autocomplete and reverse endpoints. A new pull request for the place endpoint logging is under way.

**Comment by orangejulius** [comment]
Ah, you're right! Truth be told, our code might be a little _too_ well abstracted there.

**Comment by vesameskanen** [comment]
Well abstracted indeed - I am right now separating configuration from code inside pelias api, and that adds one more layer of complexity on top of the abstraction. The purpose is that the query structure can be defined in the pelias config file.

**Comment by missinglink** [comment]
Sorry, a little late to this conversation. The [elasticsearch client](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html) has a configurable `log` property which can be used to control the verbosity of logging between the client and server.

These settings are provided by `~/pelias.json` under the property named `esclient`, that whole block is passed to the elasticsearch client when a connection is opened.

**Comment by orangejulius** [comment]
@missinglink, man this is a bummer: the debug mode of output for esclient does output the query...almost

```
Elasticsearch DEBUG: 2016-03-28T22:11:01Z
  starting request { method: 'POST',
    path: '/pelias/neighbourhood/_search',
    body: 
     { query: { filtered: [Object] },
       size: { [Number: 20] '$': 20 },
       track_scores: { [Boolean: true] '$': true },
       sort: [ '_score' ] },
    query: { search_type: 'dfs_query_then_fetch' } }
```

**Pull request merged**
