### PR TITLE
run webserver on all available cores, resolves #6

### LINKED ISSUE #6: cluster / multicore
add cluster support so express runs on all available cores

### PR DESCRIPTION
**Pull request by missinglink**
@heffergm I can see the webserver bottlenecking at 100% CPU on a single core under load, this PR spreads the load across all available cores, which should result in better parallel processing of HTTP requests.

resolves long standing issue: https://github.com/pelias/api/issues/6 using a module ebay wrote to get parallelism when using the `express` webserver module.

```bash
$ siege -c500 -r10 "http://localhost:3100/search?input=foo"

# single core
# Response time:		        0.54 secs
# Response time:		        0.52 secs

# multi core
# Response time:		        0.16 secs
# Response time:		        0.13 secs
```

### CODE REVIEW

**Comment by dianashk** [comment]
Good call! +100000

**Comment by missinglink** [comment]
**note** this may not be compatible with node `0.12`, linking https://github.com/pelias/pelias/issues/35

**Comment by heffergm** [comment]
We run 0.12.2.

**Comment by riordan** [comment]
Bravo

**Comment by hkrishna** [comment]
:+1:

**Comment by orangejulius** [comment]
nice

**Comment by missinglink** [comment]
upstream PR opened with ebay: https://github.com/cubejs/cluster2/pull/86

**Comment by hkrishna** [comment]
:+1:

**Comment by missinglink** [comment]
:boom: now passing against `0.10` and `0.12` @see: https://travis-ci.org/pelias/api/builds/73865581

**Pull request merged**
