### PR TITLE
fix labels

### PR DESCRIPTION
**Pull request by missinglink**
this issue has been annoying me for months so I just fixed it! #ragecommit

- rename `outputGenerator` -> `labelGenerator` and rename the variables to be more clear
- fix a bunch of labels, tests for:
 - `San Francisco, CA` -> `San Francisco, San Francisco County, CA`
 - `New South Wales` -> `New South Wales, Australia`
 - `West Bengal` -> `West Bengal, India`
 - `North West` -> `North West, Singapore`
 - `Arbil` -> `Arbil, Iraq`
 - `Madrid` -> `Madrid, Spain`
 - `1 Main St, United Kingdom` -> `1 Main St, Dungannon, United Kingdom`
 - `1 Grolmanstraße, Berlin` -> `1 Grolmanstraße, Berlin, Germany`

this will likely affect some of the acceptance-tests but I think it's worth the hassle

fixes https://github.com/pelias/api/issues/285
fixes https://github.com/pelias/api/issues/152
fixes https://github.com/pelias/api/issues/46

### CODE REVIEW

**Comment by riordan** [comment]
It's not healthy, but I really enjoy your `#ragecommit`s.

**Comment by missinglink** [comment]
added custom Singapore schema (it is unusual as it is both a city and a country)

`McDonald's, Singapore, Central Singapore` -> `McDonald\'s, Central Singapore, Singapore`

**Comment by orangejulius** [comment]
nice. :+1:

**Comment by dianashk** [comment]
Good to go  :airplane:

**Comment by dianashk** [comment]
If this does indeed break acceptance tests, please commit the appropriate fixes along with this.

**Pull request merged**
