### PR TITLE
Lower default reverse search radius, add a bigger radius for coarse reverse

### PR DESCRIPTION
**Pull request by orangejulius**
Defaulting to 500km for the reverse search radius means lots of records will often be searched, when we only care about the nearest ones. This PR reduces that radius to 1km (it's a bit more difficult to specify different units in the two defaults, but 1km is still quite performant).

It also adds a second default, for when any coarse layer was manually specified. This remains at 500km.

Fixes pelias/pelias#340

### CODE REVIEW

**Comment by trescube** [comment]
👍

**Comment by orangejulius** [comment]
Update on performance:

Using our [loadtest](https://github.com/pelias/loadtest) framework, our dev instance (4 r3.xlarge AWS boxes for elasticsearch), we were previously only getting 1 request/second throughput when using NYC address points from OpenAddresses to generate reverse queries.

Now we can consistently serve 40 requests/second for NYC, and 70 for a desolate area in new mexico!

**Comment by orangejulius** [comment]
Another data point: looking at the query generated with this PR, Elasticsearch would previously have to score 24 _million_ documents on a full planet build, now with the 1km radius it scores only 10k

**Comment by dianashk** [comment]
:+1:

**Pull request merged**
