### PR TITLE
Bulk search feature

### PR DESCRIPTION
**Pull request by dimfeld**
EDIT: Ignore this first paragraph. ~~I think it's ready now. DO NOT MERGE YET -- This still needs more testing before I'm confident that it's ready, but it is working in simple tests at this point so I'm posting it for feedback.~~

This PR allows you to POST a JSON array to the `/v1/search` endpoint. In response Pelias will send an `msearch` to Elasticsearch and then return an array of GeoJSON objects. The format of each GeoJSON object is unchanged.  See #432 as well. The maximum number of searches allowed in a single request can be configured by setting `bulkSizeLimit` in the Pelias JSON config; the default is currently to not enforce a limit but this probably isn't really tenable without extra functionality to split the batch into multiple msearch calls, since Elasticsearch doesn't like it if you give it too many searches at once.

Major changes:
* Addition of new msearch service, used from the search controller.
* sanitizeAll creates `req.clean` as an array. If the original request is a singleton or comes from a GET request, `sanitizeAll` marks the request with this information so that the `sendJSON` middleware can make sure that it returns an object instead of an array.
* New `iterate` helper function to allow the middlewares to work well when 

I still need to:
* Write new ciao tests to exercise the new functionality
* Look into a couple ciao tests that were failing, though I suspect these are because the Pelias index on my ES instance is still using the schema from a few months ago and needs to be recreated.
* Probably set a real default value (50? 500?) on bulkSizeLimit.

Additionally, I think the `search` ES endpoint is actually not used anymore since req.clean is always an array now. I left in the code that uses it right now but wanted to solicit feedback on how to proceed there.

### CODE REVIEW

**Comment by dimfeld** [comment]
Things are looking good so far. Here's one question: The existing behavior of the API is to not do a search when a parsing error is encountered, and this PR brings that forward into the bulk search scenario, not performing any of the searches if a parse error was encountered on any item. 

In a bulk search scenario, do you think this is still desirable, or would it be better to only cancel the searches that had errors? I'm leaning toward changing it to still perform whichever searches for whichever items were valid.

**Comment by dimfeld** [comment]
Added some ciao tests. The existing failures all passed once I created a new index that used the new schema. I also set the default limit on the POSTed array length to 50. I think this is ready to go. Please let me know if you have any comments  :)

**Comment by missinglink** [comment]
hi @dimfeld this is super exciting, we have been talking about it in our meetings here at mapzen.

our product manager @riordan will reach out to you shortly to discuss in more detail.

**Comment by dimfeld** [comment]
Any updates here? I haven't heard from anyone since the comment above and my window to do extra integration work on this is closing.

**Comment by dianashk** [comment]
Hey @dimfeld, we are so super duper sorry about how long it's been since we've last replied. 😔  🐢 

You've really done a tremendous amount of work for this and we really appreciate it! ❤️  🎆 

It's a very big change that unfortunately doesn't align with our current roadmap. However, we'd love to chat with you in a hangout about the motivation behind this work. It would help to understand why you need such a feature and how we can accommodate those needs in another way in the short-term. We'd love to connect via search@mapzen.com to setup a call if you have some time to chat with the team.
Thanks again for all of your support and hard work! 

And again, we're really really really sorry to keep you waiting for so long. 💐

**Pull request closed without merging**
